"""format_incar() — render a tag dict into a formatted INCAR string."""
from __future__ import annotations


def format_incar(tags: dict, calc_type: str) -> str:
    lines = [
        f"# job_type = {calc_type}",
        f"# INCAR for {calc_type.upper()} calculation",
        "# Generated by incar_gen.py",
        "",
    ]

    sections: dict[str, list[str]] = {
        "Startup": [
            "SYSTEM", "ISTART", "ICHARG",
        ],
        "Electronic": [
            "ENCUT", "PREC", "EDIFF", "NELM", "NELMIN", "ALGO",
            "ISMEAR", "SIGMA", "ISPIN", "MAGMOM",
            "LSORBIT", "LNONCOLLINEAR", "GGA_COMPAT",
        ],
        "vdW": [
            "IVDW",
        ],
        "Ionic": [
            "EDIFFG", "NSW", "IBRION", "POTIM", "ISIF", "ISYM",
            "MDALGO", "TEBEG", "TEEND", "SMASS", "NBLOCK", "KBLOCK",
            "LANGEVIN_GAMMA", "LANGEVIN_GAMMA_L", "PMASS", "PSTRESS",
            "NFREE",
            "IOPT", "SPRING", "IMAGES", "LCLIMB",
        ],
        "Output": [
            "LORBIT", "NEDOS", "EMIN", "EMAX", "NBANDS",
            "LWAVE", "LCHARG", "LREAL", "ADDGRID",
        ],
        "Hybrid": [
            "GGA", "LHFCALC", "HFSCREEN", "AEXX", "PRECFOCK", "TIME",
        ],
        "DFPT": [
            "LEPSILON", "LRPA",
        ],
        "LDA+U": [
            "LDAU", "LDAUTYPE", "LDAUL", "LDAUU", "LDAUJ",
            "LDAUPRINT", "LMAXMIX",
        ],
        "Parallelization": [
            "NCORE",
        ],
    }

    written: set[str] = set()
    for section, keys in sections.items():
        section_tags = {k: tags[k] for k in keys if k in tags}
        if section_tags:
            lines.append(f"# --- {section} ---")
            for k, v in section_tags.items():
                lines.append(f"  {k:<16} = {v}")
                written.add(k)
            lines.append("")

    remaining = {k: v for k, v in tags.items() if k not in written}
    if remaining:
        lines.append("# --- Other ---")
        for k, v in remaining.items():
            lines.append(f"  {k:<16} = {v}")
        lines.append("")

    return "\n".join(lines)
